### ISSUE TITLE
duration in setStart should be long type

### ISSUE THREAD

**Issue by Bresiu** [kairosdb/kairosdb-client#23]
When quering for DataPoints, it should be possible to enter long value for TimeUnit.MILLISECONDS. For example, last query has timestamp=1413537893570, and next query will be System.currentTimeMillis()-timestamp. Integer.MAX_VALUE is sometimes too small, and changing units to SECONDS/HOURS is not precise enough.

**Comment by jsabin** [comment]
This needs to be changed in KariosDB to support this. I will submit a bug for this.
