### ISSUE TITLE
Query regarding HttpClient retry mechanism

### ISSUE THREAD

**Issue by robshep** [kairosdb/kairosdb-client#26]
HttpClient has a retry mechanism.

Can I ask why the internal retry counter is incremented on every call to execute

https://github.com/kairosdb/kairosdb-client/blob/master/src/main/java/org/kairosdb/client/HttpClient.java#L85

After testing the client last night - I see that after a few thousand successful requests, when the server (on my laptop) went away (died), there were delays of more than 40 minutes between "exceptions" 

when the server recovered some time later requests were successful again, but when it went away again, the retry mechanism was still causing delays of more than an hour.

Why the ++operator at line 85?
is it meant for some kind of exponential backoff?
what if it were reset to the initial value after a successful "1st attempt" submission instead of successful submissions altering the internal state every time?

happy to provide a patch for any of this.

**Comment by jsabin** [comment]
Looks like a bug. I will take a look at it.

**Comment by jsabin** [comment]
Fixed in version #d59498fcb3bb7a527f3b644edd51fc089016efab.
