### ISSUE TITLE
project doesnt seem to build on windows eclipse

### ISSUE THREAD

**Issue by sanjayc1981** [kairosdb/kairosdb-client#32]
Hi,
Am facing a few problems trying to run this in windows eclipse.

mvn package          fails..
Running org.kairosdb.client.ClientIntegrationTest
java.io.IOException: Unable to delete file: build\h2db\kairosdb.h2.db
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2106)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1583)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1465)
seems the same process holds lock on the file.

Even after taking all the jars from kairosdb/lib and taking http-client 4.3.3
i get following error..
Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)
...
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:726)
	at org.kairosdb.client.HttpClient.<init>(HttpClient.java:50)

Can you please check?

Regards
Sanjay

**Comment by jsabin** [comment]
Were you able to get this working?

**Comment by adeliz** [comment]
I also use Eclipse (Luna - 4.4.2) with M2Eclipse on Windows. It works fine but I added some configuration in the pom.xml file (see below).
It could be added in the master repository.  It has no influence on the Maven build itself.

Could you also replace the following code (line 40) in the QueryResponseTest class in order to support any OS?
```java
json = json.replaceAll("\n", ""); // remove newlines so strings can compare
```
```java
json = json.replaceAll(System.getProperty("line.separator"), ""); // remove newlines so strings can compare
````


pom.xml addition :
```xml
<build>
...
    <pluginManagement>
        <plugins>
            <!--This plugin's configuration is used to store Eclipse m2e settings only.
                It has no influence on the Maven build itself.-->
            <plugin>
                <groupId>org.eclipse.m2e</groupId>
                <artifactId>lifecycle-mapping</artifactId>
                <version>1.0.0</version>
                <configuration>
                    <lifecycleMappingMetadata>
                        <pluginExecutions>
                            <pluginExecution>
                                <pluginExecutionFilter>
                                    <groupId>org.jacoco</groupId>
                                    <artifactId>jacoco-maven-plugin</artifactId>
                                    <versionRange>[0.5,)
                                    </versionRange>
                                    <goals>
                                        <goal>prepare-agent</goal>
                                    </goals>
                                </pluginExecutionFilter>
                                <action>
                                    <!-- m2e doesn't know what to do with jacoco,
                                        let's ignore it or annoying error markers appear
                                        see https://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html
                                     -->
                                    <ignore></ignore>
                                </action>
                            </pluginExecution>
                        </pluginExecutions>
                    </lifecycleMappingMetadata>
                </configuration>
            </plugin>
        </plugins>
    </pluginManagement>
</build>
```

**Comment by jsabin** [comment]
Thanks. Dumb error on my part. I fixed the line separator.
