### ISSUE TITLE
method addTags will not add tags because "this" keyword is missing.

### ISSUE THREAD

**Issue by chiragarora17** [kairosdb/kairosdb-client#33]
https://github.com/kairosdb/kairosdb-client/blob/master/src/main/java/org/kairosdb/client/builder/Metric.java

In Metric.java, I tried using addTags but for some reason, it wasn't adding the tags. When I debugged it, I found that you were using same name variable "tags" locally and globally and therefore, tags from map wasn't added into the global variable. Please use this.tags on line 76

**Comment by FrEaKmAn** [comment]
Yes, there is already a bug https://github.com/kairosdb/kairosdb-client/issues/27 and pull fix https://github.com/kairosdb/kairosdb-client/pull/28

@brianhks @jsabin can someone please update the client because there are few bug fixes waiting...

**Comment by jsabin** [comment]
Fixed.
