### ISSUE TITLE
Could not get datapoints in query response

### ISSUE THREAD

**Issue by bhavink24** [kairosdb/kairosdb-client#39]
Here is the sample query code
builder.setStart(2, TimeUnit.HOURS)
	.setEnd(new Date())
	.addMetric("kairosdb.datastore.query_time")
	.addAggregator(AggregatorFactory.createSumAggregator(2, TimeUnit.HOURS));
QueryResponse response = client.query(builder);

Response From Client:
response.getQueries().get(0).getResults().get(0).getDataPoints() gives 0 values

Response From Browser:
{"queries":[{"sample_size":6,"results":[{"name":"kairosdb.datastore.query_time","values":[[1432131822647,12],[1432132493439,177]]}]}]}

**Comment by FrEaKmAn** [comment]
Try printing out

    builder.build()

It will show you built request so you can compare it with your browser request.

**Comment by bhavink24** [comment]
Request/Response From Client and Browser

From Client
Request
{"end_absolute":1432211465797,"start_relative":{"value":2,"unit":"HOURS"},"cacheTime":0,"metrics":[{"name":"kairosdb.datastore.query_time","tags":{},"group_by":[],"aggregators":[{"sampling":{"value":2,"unit":"HOURS"},"name":"sum"}]}]}

Response
{"queries":[{"results":[{"name":"kairosdb.datastore.query_time","tags":{"host":["localhost"],"metric_name":["kairosdb.datastore.cassandra.key_query_time","kairosdb.datastore.query_time"],"query_index":["1"]},"values":[]}],"sample_size":5}],"statusCode":200,"errors":[]}

From Browser
Request
{"metrics":[{"tags":{},"name":"kairosdb.datastore.cassandra.key_query_time","aggregators":[{"name":"sum","align_sampling":true,"sampling":{"value":"2","unit":"hours"}}]}],"cache_time":0,"start_relative":{"value":"2","unit":"hours"}}

Response
{"queries":[{"sample_size":7,"results":[{"name":"kairosdb.datastore.cassandra.key_query_time","tags":{"host":["localhost"],"metric_name":["kairosdb.datastore.cassandra.key_query_time","kairosdb.datastore.query_time"],"query_index":["1"],"request":["/datapoints/query"]},"values":[[1432211488949,10]]}]}]
}

**Comment by FrEaKmAn** [comment]
As you can see, returned datapoint has greater timestamp than client end_absolute. Do you have all times in sync?

**Comment by bhavink24** [comment]
I have everything running on localhost only, both KairosDB and Cassandra. Default value for end_relative is current time, however I tried changing it to end_relative for both client and browser. I still don't get datapoint values in client. Not sure if I am doing something wrong, posting all the data again.

Client Request
{"start_relative":{"value":1,"unit":"HOURS"},"end_relative":{"value":1,"unit":"SECONDS"},"cacheTime":0,"metrics":[{"name":"kairosdb.datastore.query_time","tags":{},"group_by":[],"aggregators":[{"sampling":{"value":1,"unit":"HOURS"},"name":"sum"}]}]}

Client Response
{"queries":[{"results":[{"name":"kairosdb.datastore.query_time","tags":{"host":["localhost"],"metric_name":["kairosdb.datastore.query_time","kairosdb.http.query_time","kairosdb.jvm.thread_count"],"query_index":["1"],"request":["/datapoints/query"]},"values":[]}],"sample_size":67}],"statusCode":200,"errors":[]}


Browser Request
{"metrics":[{"tags":{},"name":"kairosdb.datastore.query_time","aggregators":[{"name":"sum","align_sampling":true,"sampling":{"value":"1","unit":"hours"}}]}],"cache_time":0,"start_relative":{"value":"1","unit":"hours"},"end_relative":{"value":"1","unit":"seconds"}}

Browser Response
{"queries":[{"sample_size":70,"results":[{"name":"kairosdb.datastore.query_time","tags":{"host":["localhost"],"metric_name":["kairosdb.datastore.query_time","kairosdb.http.query_time","kairosdb.jvm.thread_count"],"query_index":["1"],"request":["/datapoints/query"]},"values":[[1432221158594,563]]}]}]}

sample_size matches, but values is null with client.

**Comment by FrEaKmAn** [comment]
Which version of client are you using? The one from maven or master?

**Comment by bkansara** [comment]
It is with maven dependency

http://mvnrepository.com/artifact/org.kairosdb/client/2.0
<dependency>
	<groupId>org.kairosdb</groupId>
	<artifactId>client</artifactId>
	<version>2.0</version>
</dependency>

**Comment by jsabin** [comment]
Let's eliminate the possibility that is a time problem. Remove ".setEnd(new Date())" from you query. The query will assume NOW as the end time. Let me know if this solves the problem.

**Comment by bkansara** [comment]
I tried without .setEnd from the query, but still don't have values in response

**Comment by FrEaKmAn** [comment]
Is KairosDB behind some load balancer/proxy?

I use same client and no problems at all.

**Comment by bhavink24** [comment]
It is running on my local machine, and don't have any proxy.

**Comment by bhavink24** [comment]
I did some more debugging and found this:

ResultsDeserializer.java - line 32 - variable JsonElement is with this following json
{"name":"kairosdb.datastore.query_time","tags":{"host":["PRINHYLTPHP0066"],"metric_name":["kairosdb.datastore.query_time"],"query_index":["1"],"request":["/datapoints/query"]},"values":[[1432538566295,426]]}

and line-72 variable datapoints is with 0 values.

I think, this is because group_by is not having any value (line 48). So, datapoint is not populated. Any specific values we have to give for group_by or it is optional?

**Comment by FrEaKmAn** [comment]
Could be a bug in groupby. Try 

    .addGrouper(new TagGrouper("name"));

to group by tag (in my case it's name, yours is host)

**Comment by bhavink24** [comment]
I tried TestCases for ClientIntegrationTest.java (org.kairosdb.client) and here are observations for test_httpClient_multiTagValues() method.
1) Works fine with InMemoryKairosServer for test cases
2) If I execute without InMemoryKairosServer  (i.e by not executing the test setup code @AfterClass, @BeforeClass etc) and instead use a live KariosDB instance the test will fail. 

My application code is similar to the code in ClientIntegrationTest, the method being test_httpClient_multiTagValues().

**Comment by jsabin** [comment]
The problem is that the client supports version 0.94+ of KairosDB which always returns a type in the group_by field. Since no type is returned, the client doesn't understand which type of data it is an thus does not return any data. 

I will look at the possibility of supporting older version of KairosDB.

**Comment by bhavink24** [comment]
Upgrading to kairosdb-0.9.4 resolved the issue.  Thanks for the support.
