### ISSUE TITLE
QueryResponse response = client.query(builder) produces unknown messages

### ISSUE THREAD

**Issue by baderas** [kairosdb/kairosdb-client#43]
When I run

"QueryResponse response = client.query(builder);" (without "")

in my Code, there is always a message dropped:

"******************\* Type=number" (without "")

I think it it from GSON or Apache's Httpclient (bot inside kairosdb-client), but I can't turn it off and I don't know where it exactly comes from. I searched inside kairosdb-client, but found no point where a Message like this seems to be produced.

It is also not an error or warning.

Can you help me turn this mesage off?

**Comment by FrEaKmAn** [comment]
This is an old debug message that was left out in the client. It was removed in the latest version. @jsabin @brianhks can we get a newer release published to maven?

**Comment by jsabin** [comment]
Yes this has been removed. I will be building a new client soon.
