### ISSUE TITLE
Allow user to set maximum connection per route

### ISSUE THREAD

**Issue by carysyd** [kairosdb/kairosdb-client#47]
From my understanding, KairosDB Java Client uses Apache Http Client behind the scene. It's using default value of 2 in max connection per route. I have a multi-threaded application that shares the same KairosDB client instance, but I had to write a subclass to extend Kairos HttpClient so I can pass in a new Apache Http Client with a higher max connection count.

It would be nice if the max connection per route is configurable in the default client.

**Comment by jsabin** [comment]
I added a constructor that takes an HttpClientBuilder to allow properties set. See 1c39647
