### ISSUE TITLE
Support auto reconnect if Kairos goes down

### ISSUE THREAD

**Issue by brianhks** [kairosdb/kairosdb-client#52]
If Kairos goes down and comes back the client doesn't reconnect to send data.

**Comment by DanoOM** [comment]
Sorry, I reported this 'behavior' on the kairosdb google-groups, but i have since confirmed it was in fact a bug in my code not properly handling the Exception from the the client.

-- Feel free to close it out.

**Comment by brianhks** [comment]
No problem.  Just don't want issues to drop between the cracks.
