### ISSUE TITLE
NullPointerException when creating a DataGapsMarkingAggregator

### ISSUE THREAD

**Issue by jprivillaso** [kairosdb/kairosdb-client#54]
I am trying to create a DataGapsMarkingAggregator from a java test, and it throws a NullPointerException when trying to deserialize the response.

As some of the values will return null, and that is exactly what I want, JsonMapper throws a NullPointerException

`mapper.fromJson(json, typeOfT);`

I debugged the code and the method `getBody(stream);` is returning the data correctly. Then it throws the exception inside Class QueryResponse, Line 75, 

`KairosQueryResponse response = mapper.fromJson(body, KairosQueryResponse.class);`

I am using KairosDb-Client version 2.1.1
Furthermore, Is there a way to tell kairos explicitly to ignore null values or what should I do? 

Thank you!

**Comment by jsabin** [comment]
Fixed in commit 3937f43dee45b3e1e97a723d30fc3326f3d3ba5e.
