### ISSUE TITLE
exclude_tags option is not supported in client

### ISSUE THREAD

**Issue by raisudeen** [kairosdb/kairosdb-client#57]
Hi,

I couldn't fine **exclude_tags** option for QueryMetrics in Java Client API. I think, it is not supported in client. Can you please let me know the API if already supported? or Kindly add "exclude_tags" option in QueryMetrics. Thanks in advance.

http://kairosdb.github.io/docs/build/html/restapi/QueryMetrics.html#metric-properties

-Raisudeen.

**Comment by jsabin** [comment]
Added exclude_tags.

d17bb285646a2628afe2c78aa40f516987304a3c
