### ISSUE TITLE
Unable to push metrics using kairosdb client

### ISSUE THREAD

**Issue by shukad33** [kairosdb/kairosdb-client#63]
Hi ,

While pushing metrics using metric builder , I am getting the below error : 

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/HttpResponse
	at com.kairosdb.KairosPushTest.main(KairosPushTest.java:24)
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpResponse
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

I am using client version 2.2.0 .

**Comment by jsabin** [comment]
Sorry for the delayed response. This issues slipped by me.

Perhaps this is a conflict of dependencies. The client uses this version of HTTP Apache client.
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.3.3</version>
		</dependency>

If you are using maven you can run "mvn dependency::tree" to see what your dependencies are.

**Comment by jolcese** [comment]
Hi @jsabin, can you please post an example of the libraries you're importing? I'm facing the same issue.

**Comment by jsabin** [comment]
Here are the dependencies. I highlighted the apached http client dependencies.

[INFO] org.kairosdb:client:jar:2.2.0
[INFO] +- com.google.guava:guava:jar:14.0:compile
[INFO] +- org.hamcrest:hamcrest-all:jar:1.1:test
_**[INFO] +- org.apache.httpcomponents:httpclient:jar:4.3.3:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.3.2:compile**_
[INFO] |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.6:compile
[INFO] +- commons-lang:commons-lang:jar:2.6:compile
[INFO] +- commons-io:commons-io:jar:2.2:compile
[INFO] +- com.google.code.findbugs:jsr305:jar:2.0.0:compile
[INFO] +- junit:junit:jar:4.11:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- com.google.code.gson:gson:jar:2.2.4:compile
[INFO] +- org.kairosdb:kairosdb:jar:1.1.3-1:test
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.4:test
[INFO] |  +- org.json:org.json:jar:chargebee-1.0:test
[INFO] |  +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] |  +- io.netty:netty:jar:3.10.6.Final:test
[INFO] |  +- com.google.inject:guice:jar:3.0:test
[INFO] |  |  +- javax.inject:javax.inject:jar:1:test
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:test
[INFO] |  +- com.google.inject.extensions:guice-multibindings:jar:3.0:test
[INFO] |  +- com.google.inject.extensions:guice-servlet:jar:3.0:test
[INFO] |  +- com.h2database:h2:jar:1.3.170:test
[INFO] |  +- c3p0:c3p0:jar:0.9.1.2:test
[INFO] |  +- org.slf4j:jul-to-slf4j:jar:1.7.2:test
[INFO] |  |  \- org.slf4j:slf4j-api:jar:1.7.2:test
[INFO] |  +- org.apache.commons:commons-math3:jar:3.2:test
[INFO] |  +- com.beust:jcommander:jar:1.35:test
[INFO] |  +- joda-time:joda-time:jar:2.3:test
[INFO] |  +- ch.qos.logback:logback-core:jar:1.1.7:test
[INFO] |  +- ch.qos.logback:logback-classic:jar:1.1.7:test
[INFO] |  +- org.agileclick.genorm:genormous:jar:1.6.0.jdbc4:test
[INFO] |  |  +- org.antlr:stringtemplate:jar:3.2.1:test
[INFO] |  |  |  \- antlr:antlr:jar:2.7.7:test
[INFO] |  |  \- dom4j:dom4j:jar:1.6.1:test
[INFO] |  |     \- xml-apis:xml-apis:jar:1.0.b2:test
[INFO] |  +- jaxen:jaxen:jar:1.1.6:test
[INFO] |  +- org.hectorclient:hector-core:jar:1.1-4:test
[INFO] |  |  +- commons-pool:commons-pool:jar:1.5.3:test
[INFO] |  |  +- org.apache.cassandra:cassandra-thrift:jar:1.2.5:test
[INFO] |  |  |  \- org.apache.thrift:libthrift:jar:0.7.0:test
[INFO] |  |  +- com.github.stephenc.eaio-uuid:uuid:jar:3.2.0:test
[INFO] |  |  +- com.ecyrd.speed4j:speed4j:jar:0.9:test
[INFO] |  |  \- com.yammer.metrics:metrics-core:jar:2.2.0:test
[INFO] |  +- org.eclipse.jetty:jetty-server:jar:8.1.16.v20140903:test
[INFO] |  |  +- org.eclipse.jetty:jetty-continuation:jar:8.1.16.v20140903:test
[INFO] |  |  \- org.eclipse.jetty:jetty-http:jar:8.1.16.v20140903:test
[INFO] |  |     \- org.eclipse.jetty:jetty-io:jar:8.1.16.v20140903:test
[INFO] |  +- org.eclipse.jetty:jetty-servlet:jar:8.1.16.v20140903:test
[INFO] |  |  \- org.eclipse.jetty:jetty-security:jar:8.1.16.v20140903:test
[INFO] |  +- org.eclipse.jetty:jetty-servlets:jar:8.1.16.v20140903:test
[INFO] |  |  +- org.eclipse.jetty:jetty-client:jar:8.1.16.v20140903:test
[INFO] |  |  \- org.eclipse.jetty:jetty-util:jar:8.1.16.v20140903:test
[INFO] |  +- org.eclipse.jetty.orbit:javax.servlet:jar:3.0.0.v201112011016:test
[INFO] |  +- com.sun.jersey.contribs:jersey-guice:jar:1.18.3:test
[INFO] |  +- com.sun.jersey:jersey-server:jar:1.18.3:test
[INFO] |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.2.3:test
[INFO] |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.2.3:test
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.2.3:test
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.2.3:test
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.2.3:test
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.2.3:test
[INFO] |  +- com.sun.jersey:jersey-core:jar:1.18.3:test
[INFO] |  +- com.sun.jersey:jersey-servlet:jar:1.18.3:test
[INFO] |  +- com.sun.jersey.contribs.jersey-oauth:oauth-signature:jar:1.18.3:test
[INFO] |  +- com.sun.jersey.contribs.jersey-oauth:oauth-server:jar:1.18.3:test
[INFO] |  +- javax.validation:validation-api:jar:1.0.0.GA:test
[INFO] |  +- org.apache.bval:bval-jsr303:jar:0.5:test
[INFO] |  |  \- org.apache.bval:bval-core:jar:0.5:test
[INFO] |  |     \- commons-beanutils:commons-beanutils-core:jar:1.8.3:test
[INFO] |  +- org.quartz-scheduler:quartz:jar:2.1.7:test
[INFO] |  +- com.codahale.metrics:metrics-healthchecks:jar:3.0.2:test
[INFO] |  \- com.codahale.metrics:metrics-jvm:jar:3.0.2:test
[INFO] |     \- com.codahale.metrics:metrics-core:jar:3.0.2:test
[INFO] \- org.mockito:mockito-core:jar:1.9.5:test
[INFO]    \- org.objenesis:objenesis:jar:1.0:test
