### ISSUE TITLE
Custom HttpClient support

### ISSUE THREAD

**Issue by SchutzeHades** [kairosdb/kairosdb-client#67]
Hi, I noticed that this client uses org.apache.http.client.HttpClient and provides a constructor taking an HttpClientBuilder as a parameter. But in my situation, I want one more constructor that takes an org.apache.http.client.HttpClient as a parameter, because my http client is created by another library and there's no way to get that kind of builder object. Currently I extends org.kairosdb.client.HttpClient and replace the inner client using org.kairosdb.client.HttpClient#setClient method which is intended to be a test method. I suppose this may be a common situation and wonder if there are any plans to support this. Thank you.

**Comment by jsabin** [comment]
Fixed in 7b7fd3f48be17b86d10062ce6f0f550a4f3a32ed in the development branch.
