### ISSUE TITLE
It is the bug when I push the string "127.0.0.1"

### ISSUE THREAD

**Issue by dahaian** [kairosdb/kairosdb-client#73]
this is my code
`MetricBuilder builder = MetricBuilder.getInstance();

builder.addMetric("metric1")
    .addTag("host", "server1")
    .addTag("customer", "Acme")
    .addDataPoint(System.currentTimeMillis(), "127.0.0.1");
HttpClient client = new HttpClient("http://localhost:8080");
Response response = client.pushMetrics(builder);
client.shutdown();`

I run the code but I got errors: multiple points
I think it is the bug.Any help is appreciated.

**Comment by martin-g** [comment]
You are hitting this bug: https://github.com/kairosdb/kairosdb/pull/476. See the linked issue too.

**Comment by jsabin** [comment]
The KairosDB #476 has been fixed.
