### ISSUE TITLE
Cannot create SamplingAggregator with align_end_time 

### ISSUE THREAD

**Issue by pkokoshnikov** [kairosdb/kairosdb-client#75]
I needed to create an aggregator with end time aligment. But class SamplingAggregator doesn't have such field and such method. Yes this issue has a workaround: to create subcluss from SamplingAggregator, but i looks ugly. Guys please add align_end_time to your SamplingAggregator.

**Comment by pkokoshnikov** [comment]
https://github.com/kairosdb/kairosdb-client/pull/76

**Comment by jsabin** [comment]
Merged issue #76.
