### ISSUE TITLE
QueryTagBuilder   the range time is not effect  bug

### ISSUE THREAD

**Issue by erge-plus** [kairosdb/kairosdb-client#84]
QueryTagBuilder queryTagBuilder = QueryTagBuilder.getInstance();
queryTagBuilder.addMetric("aaa".toUpperCase());
queryTagBuilder.setStart(new Date(1357023600000L));
queryTagBuilder.setEnd(new Date(1357023600006L));

the result is all tags , not the range time's tag

I guess the reason may be :
set
HttpClient
((HttpPost) apacheRequest).setEntity(((StringBodySource) request.getBodySource()).toHttpEntity());

get
ProtocolExec
HttpParams params = request.getParams();

**Comment by BrentonPoke** [comment]
I'm having trouble understanding why those two lines are at fault. Can you walk me through how you got here?

**Comment by erge-plus** [comment]
> I'm having trouble understanding why those two lines are at fault. Can you walk me through how you got here?

the first set the query time, the second get the query time,  maybe it is not the reason, it is only my guess.   In fact ,when i use QueryTagBuilder ,I set the range time ,but it not effect.

**Comment by erge-plus** [comment]
so so
