### ISSUE TITLE
Importing the wrong NotImplementedException

### ISSUE THREAD

**Issue by Pekallinen** [kairosdb/kairosdb-client#92]
Hello,

In [ResponseHelper.java](https://github.com/kairosdb/kairosdb-client/blob/ecc845b7e4875b35b735bf18f6460f3e8f2152d3/src/main/java/org/kairosdb/client/response/ResponseHelper.java#L6), you are importing `sun.reflect.generics.reflectiveObjects.NotImplementedException` instead of `org.apache.commons.lang3.NotImplementedException`.

https://www.oracle.com/java/technologies/faq-sun-packages.html

**Comment by brianhks** [comment]
Thanks fixed.
